# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  ec2_ip: "13.203.159.242"
  ec2_user: "ubuntu"
  ssh_key: "$(ssh-key)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: default
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "docker-hub-registry"
              repository: "heyanoop/eatables"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
          - script: docker builder prune -f
            displayName: clear builder cache
  - stage: Deploy
    dependsOn: Build
    displayName: deploy to ec2 instance
    jobs:
      - job: Deploy
        displayName: deploy to ec2
        pool: default
        steps:
          - script: |
              - script: |
                  mkdir -p ~/.ssh
                  # Write the key with proper newlines
                  echo "$(ssh_key)" | base64 -d > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $(ec2_ip) >> ~/.ssh/known_hosts

                  ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $(ec2_user)@$(ec2_ip) << EOF
                    docker stop eatables || true
                    docker rm eatables || true
                    echo y | docker system prune -a
                    docker run -d --name eatables --env-file .env -p 3000:5000 heyanoop/eatables:$(tag)
                  EOF
                displayName: Deploy application
