version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "No pre-build steps are required as there are no tests or builds."

  build:
    commands:
      - echo "Starting the application temporarly to ensure it runs without errors..."
      - node --check index.js

  post_build:
    commands:
      - echo "Build phase completed thank you"
      

artifacts:
  files:
    - '**/*' 
  discard-paths: no
