name: Deploy Docker Image to EC2

on:
  workflow_run:
    workflows:
      - build docker image
    types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 15.207.249.95 >> ~/.ssh/known_hosts

      - name: Pull and Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.207.249.95 << 'EOF'
            docker pull docker push heyanoop/eatables:9
            docker stop eatables || true
            docker rm eatables || true
            docker run -d --name eatables -p 3000:5000 heyanoop/eatables:9
          EOF
