name: Deploy Docker Image to EC2

on:
  workflow_run:
    workflows:
      - build docker image
    types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.203.159.242 >> ~/.ssh/known_hosts

      - name: Pull and Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.203.159.242 << 'EOF'
            docker stop eatables || true
            docker rm eatables || true
            echo y | docker system prune -a
            docker run -d --name eatables --env-file .env -p 3000:5000 heyanoop/eatables:${{ github.run_number }}
          EOF
